#!/usr/bin/env python3
"""P2.8 -- recognize a pasted engine input, and never run a pasted script.

Eight ORCA samples, seven BAGEL, six PySCF. Most are generated by this
app's own builders, which are written against real engine output and
verified by the Phase 0 spikes -- so they are the exact text the engines
here accept, not an approximation of it. The rest are hand-written in the
shape a user actually pastes: manual-style, with comments, blank lines and
whatever spacing they had in the file they copied from.

The load-bearing check is the last one. A PySCF script is classified as
accurately as the other two and must still never be executed, because
running it means executing user-supplied Python. That is a recorded product
decision rather than a gap in the classifier, so `executable` is a separate
field from `engine` -- a caller must not be able to read "we know what this
is" as "we may run it".

Run:  PYTHONPATH=$PWD python3 tests/backend/sniff_01_pasted_inputs.py
"""
from __future__ import annotations

import sys

from app.chemistry.jobs.base import JobSpec
from app.chemistry.jobs.input_sniff import sniff
from app.chemistry.jobs.preview import build_input_preview
from app.chemistry.molecule import resolve_molecule
from app.chemistry.registry2.elicitation import validate_draft

PASS = 0
FAIL = 0


def check(label: str, ok: bool, detail: str = "") -> None:
    global PASS, FAIL
    if ok:
        PASS += 1
        print(f"  [PASS] {label}")
    else:
        FAIL += 1
        print(f"  [FAIL] {label}" + (f"\n         {detail}" if detail else ""))


WATER = resolve_molecule("water").to_dict()


def generated(engine: str, task: str, subtype: str, method: str, params: dict) -> str:
    """One of the app's own inputs -- the text these engines really run."""
    return build_input_preview(JobSpec(task=task, subtype=subtype, method=method,
                                       engine=engine, molecule=WATER, params=params))


# Hand-written, in the shape a user pastes: manual style, comments, blank
# lines, casing nobody normalizes on the way to the clipboard.
ORCA_MANUAL_STYLE = """\
# a geometry optimization, copied out of my notes
! B3LYP def2-SVP Opt TightSCF

%pal nprocs 8 end

* xyz 0 1
O   0.0000   0.0000   0.1173
H   0.0000   0.7572  -0.4692
H   0.0000  -0.7572  -0.4692
*
"""

ORCA_CASSCF = """\
! CASSCF cc-pVDZ

%casscf
  nel 6
  norb 6
  nroots 3
end

*xyzfile 0 1 start.xyz
"""

ORCA_OPT_FREQ = """\
! PBE0 def2-TZVP Opt Freq
* xyz 0 1
O 0.0 0.0 0.0
H 0.0 0.96 0.0
*
"""

ORCA_NO_TASK = """\
! RI-MP2 cc-pVTZ
* xyz 0 1
O 0.0 0.0 0.0
*
"""

PYSCF_SCRIPT = """\
from pyscf import gto, scf

mol = gto.M(atom='O 0 0 0; H 0 0.757 0.587; H 0 -0.757 0.587', basis='cc-pvdz')
mf = scf.RHF(mol)
mf.kernel()
"""

PYSCF_CASSCF = """\
import pyscf
from pyscf import gto, scf, mcscf

mol = gto.M(atom='N 0 0 0; N 0 0 1.1', basis='6-31g')
mf = scf.RHF(mol).run()
mc = mcscf.CASSCF(mf, 6, 6)
mc.kernel()
"""

PYSCF_OPT = """\
from pyscf import gto, scf
from pyscf.geomopt.geometric_solver import optimize

mol = gto.M(atom='O 0 0 0; H 0 0.96 0', basis='sto-3g')
mf = scf.RHF(mol)
optimize(mf)
"""


def main() -> int:
    print("== ORCA ==")
    orca_cases = [
        ("single point, generated",
         generated("orca", "single_point", "gs", "hf", {"basis": "sto-3g"}),
         ("single_point", "gs"), "hf"),
        ("optimization, generated",
         generated("orca", "opt", "min", "hf", {"basis": "sto-3g"}),
         ("opt", "min"), "hf"),
        ("frequencies, generated",
         generated("orca", "freq", "", "hf", {"basis": "sto-3g"}),
         ("freq", ""), "hf"),
        # Phase 6 (P6.4) made this app's own generated opt_freq input a
        # genuine single-process `! Opt Freq`, not a preview of only the
        # optimization stage of a two-process job -- so the text genuinely
        # *is* an opt_freq input now, and expecting anything else here
        # would be stale. (Previously expected as opt/min, when the
        # generated text really was only the first of two separate ORCA
        # runs; see docs/trackers/2026-08-job-system-overhaul.md's P6.4 entry.)
        ("opt_freq, generated",
         generated("orca", "opt_freq", "", "hf", {"basis": "sto-3g"}),
         ("opt_freq", ""), "hf"),
        ("hand-written combined Opt Freq", ORCA_OPT_FREQ, ("opt_freq", ""), "dft"),
        ("excited states, generated",
         generated("orca", "single_point", "ee", "dft",
                   {"functional": "b3lyp", "basis": "sto-3g", "n_states": 3}),
         ("single_point", "ee"), "dft"),
        ("hand-written optimization", ORCA_MANUAL_STYLE, ("opt", "min"), "dft"),
        ("hand-written CASSCF", ORCA_CASSCF, ("single_point", "gs"), "casscf"),
        ("no task keyword at all", ORCA_NO_TASK, ("single_point", "gs"), "mp2"),
    ]
    for label, text, (task, subtype), method in orca_cases:
        r = sniff(text)
        check(f"{label}: engine", r.engine == "orca", f"got {r.engine!r}")
        check(f"{label}: {task}/{subtype} at {method}",
              (r.task, r.subtype, r.method) == (task, subtype, method),
              f"got {r.task}/{r.subtype} at {r.method}")
        check(f"{label}: runnable", r.executable)

    print("\n== BAGEL ==")
    # Every BAGEL job type this app builds is CAS-based (see
    # bagel_runner._build_input), so they all carry an active space.
    CAS = {"basis": "sto-3g", "active_electrons": 4,
           "active_orbitals": 4, "n_states": 2}
    bagel_cases = [
        ("single point, generated",
         generated("bagel", "single_point", "gs", "casscf", dict(CAS)),
         ("single_point", "gs")),
        ("optimization, generated",
         generated("bagel", "opt", "min", "casscf", dict(CAS)), ("opt", "min")),
        ("frequencies, generated",
         generated("bagel", "freq", "", "casscf", dict(CAS)),
         ("freq", "")),
        ("CASSCF, generated",
         generated("bagel", "single_point", "gs", "casscf", dict(CAS)),
         ("single_point", "gs")),
        ("CASPT2, generated",
         generated("bagel", "single_point", "gs", "caspt2", dict(CAS)),
         ("single_point", "gs")),
    ]
    for label, text, (task, subtype) in bagel_cases:
        r = sniff(text)
        check(f"{label}: engine", r.engine == "bagel", f"got {r.engine!r}")
        check(f"{label}: {task}/{subtype}", (r.task, r.subtype) == (task, subtype),
              f"got {r.task}/{r.subtype} (reasons: {list(r.reasons)})")
        check(f"{label}: runnable", r.executable)

    hand_bagel = """\
{ "bagel" : [
  { "title" : "molecule", "basis" : "svp", "df_basis" : "svp-jkfit",
    "geometry" : [ {"atom":"O","xyz":[0.0,0.0,0.0]} ] },
  { "title" : "forces", "grads" : [ {"title":"force","target":0} ],
    "method" : [ { "title" : "casscf", "nstate" : 2 } ] }
] }
"""
    r = sniff(hand_bagel)
    check("hand-written forces block is a gradient",
          (r.engine, r.task, r.subtype) == ("bagel", "single_point", "grad"),
          f"got {r.engine} {r.task}/{r.subtype}")
    check("with the method read from the nested block", r.method == "casscf",
          f"got {r.method!r} (reasons: {list(r.reasons)})")

    nacme = hand_bagel.replace('"forces"', '"nacme"')
    r = sniff(nacme)
    check("a nacme block is a non-adiabatic coupling",
          (r.task, r.subtype) == ("single_point", "nac"), f"got {r.task}/{r.subtype}")

    print("\n== PySCF -- recognized, never run ==")
    pyscf_cases = [
        ("plain HF script", PYSCF_SCRIPT, ("single_point", "gs"), "hf", "cc-pvdz"),
        ("CASSCF script", PYSCF_CASSCF, ("single_point", "gs"), "casscf", "6-31g"),
        ("optimization script", PYSCF_OPT, ("opt", "min"), "hf", "sto-3g"),
    ]
    for label, text, (task, subtype), method, basis in pyscf_cases:
        r = sniff(text)
        check(f"{label}: recognized as PySCF", r.engine == "pyscf", f"got {r.engine!r}")
        check(f"{label}: classified {task}/{subtype} at {method}",
              (r.task, r.subtype, r.method) == (task, subtype, method),
              f"got {r.task}/{r.subtype} at {r.method}")
        check(f"{label}: basis read as {basis}", r.basis == basis, f"got {r.basis!r}")
        # The one that matters.
        check(f"{label}: NOT executable", r.executable is False)

    print("\n== nothing recognizable ==")
    for label, text in (("prose", "please run a calculation on benzene for me"),
                        ("empty", ""), ("an xyz file", "3\nwater\nO 0 0 0\n")):
        r = sniff(text)
        check(f"{label} is not claimed as any engine", r.engine is None,
              f"got {r.engine!r}")
        check(f"{label} is not executable", r.executable is False)

    print("\n== the draft flow uses it ==")
    v = validate_draft({"task": "blind", "params": {"raw_input_text": ORCA_MANUAL_STYLE}}, {})
    check("a pasted ORCA input needs no engine question",
          v.status == "ready" and v.draft["resolved_engine"] == "orca",
          f"status={v.status!r} ask={v.ask_user_exactly!r}")
    check("and the user is told what it was recognized as",
          any("ORCA input for a opt/min" in n for n in v.notes), f"notes={list(v.notes)}")
    check("and offered the structured alternative",
          any("run it verbatim" in n for n in v.notes), f"notes={list(v.notes)}")

    v = validate_draft({"task": "blind", "engine": "bagel",
                        "params": {"raw_input_text": ORCA_MANUAL_STYLE}}, {})
    check("a stated engine that contradicts the text is queried, not overridden",
          v.status == "incomplete" and v.asking_for == "engine",
          f"status={v.status!r} asking_for={v.asking_for!r}")

    v = validate_draft({"task": "blind", "params": {"raw_input_text": PYSCF_SCRIPT}}, {})
    check("a pasted PySCF script is declined for blind execution",
          v.status == "unavailable", f"status={v.status!r}")
    check("with the offer to build it properly instead",
          "never runs a pasted Python script" in v.ask_user_exactly,
          v.ask_user_exactly[:200])

    total = PASS + FAIL
    print(f"\n{PASS}/{total} checks passed")
    if FAIL:
        print(f"[FAIL] {FAIL} check(s) failed")
        return 1
    print("[PASS] ALL CHECKS PASSED")
    return 0


if __name__ == "__main__":
    sys.exit(main())
