#!/usr/bin/env python3
"""P2.8 -- recognize a pasted engine input, and never run a pasted script.

Eight ORCA samples, seven BAGEL, six PySCF. Most are generated by this
app's own builders, which are written against real engine output and
verified by the Phase 0 spikes -- so they are the exact text the engines
here accept, not an approximation of it. The rest are hand-written in the
shape a user actually pastes: manual-style, with comments, blank lines and
whatever spacing they had in the file they copied from.

The load-bearing check is the last one. A PySCF script is classified as
accurately as the other two and must still never be executed, because
running it means executing user-supplied Python. That is a recorded product
decision rather than a gap in the classifier, so `executable` is a separate
field from `engine` -- a caller must not be able to read "we know what this
is" as "we may run it".

Run:  PYTHONPATH=$PWD python3 tests/backend/sniff_01_pasted_inputs.py
"""
from __future__ import annotations

import json
import sys

from app.chemistry.jobs.base import JobSpec
from app.chemistry.jobs.input_sniff import sniff
from app.chemistry.jobs.preview import build_input_preview
from app.chemistry.molecule import resolve_molecule
from app.chemistry.registry2.elicitation import validate_draft

PASS = 0
FAIL = 0


def check(label: str, ok: bool, detail: str = "") -> None:
    global PASS, FAIL
    if ok:
        PASS += 1
        print(f"  [PASS] {label}")
    else:
        FAIL += 1
        print(f"  [FAIL] {label}" + (f"\n         {detail}" if detail else ""))


WATER = resolve_molecule("water").to_dict()


def generated(engine: str, task: str, subtype: str, method: str, params: dict) -> str:
    """One of the app's own inputs -- the text these engines really run."""
    return build_input_preview(JobSpec(task=task, subtype=subtype, method=method,
                                       engine=engine, molecule=WATER, params=params))


# Hand-written, in the shape a user pastes: manual style, comments, blank
# lines, casing nobody normalizes on the way to the clipboard.
ORCA_MANUAL_STYLE = """\
# a geometry optimization, copied out of my notes
! B3LYP def2-SVP Opt TightSCF

%pal nprocs 8 end

* xyz 0 1
O   0.0000   0.0000   0.1173
H   0.0000   0.7572  -0.4692
H   0.0000  -0.7572  -0.4692
*
"""

ORCA_CASSCF = """\
! CASSCF cc-pVDZ

%casscf
  nel 6
  norb 6
  nroots 3
end

*xyzfile 0 1 start.xyz
"""

ORCA_OPT_FREQ = """\
! PBE0 def2-TZVP Opt Freq
* xyz 0 1
O 0.0 0.0 0.0
H 0.0 0.96 0.0
*
"""

ORCA_NO_TASK = """\
! RI-MP2 cc-pVTZ
* xyz 0 1
O 0.0 0.0 0.0
*
"""

PYSCF_SCRIPT = """\
from pyscf import gto, scf

mol = gto.M(atom='O 0 0 0; H 0 0.757 0.587; H 0 -0.757 0.587', basis='cc-pvdz')
mf = scf.RHF(mol)
mf.kernel()
"""

PYSCF_CASSCF = """\
import pyscf
from pyscf import gto, scf, mcscf

mol = gto.M(atom='N 0 0 0; N 0 0 1.1', basis='6-31g')
mf = scf.RHF(mol).run()
mc = mcscf.CASSCF(mf, 6, 6)
mc.kernel()
"""

PYSCF_OPT = """\
from pyscf import gto, scf
from pyscf.geomopt.geometric_solver import optimize

mol = gto.M(atom='O 0 0 0; H 0 0.96 0', basis='sto-3g')
mf = scf.RHF(mol)
optimize(mf)
"""


def main() -> int:
    print("== ORCA ==")
    orca_cases = [
        ("single point, generated",
         generated("orca", "single_point", "gs", "hf", {"basis": "sto-3g"}),
         ("single_point", "gs"), "hf"),
        ("optimization, generated",
         generated("orca", "opt", "min", "hf", {"basis": "sto-3g"}),
         ("opt", "min"), "hf"),
        ("frequencies, generated",
         generated("orca", "freq", "", "hf", {"basis": "sto-3g"}),
         ("freq", ""), "hf"),
        # Phase 6 (P6.4) made this app's own generated opt_freq input a
        # genuine single-process `! Opt Freq`, not a preview of only the
        # optimization stage of a two-process job -- so the text genuinely
        # *is* an opt_freq input now, and expecting anything else here
        # would be stale. (Previously expected as opt/min, when the
        # generated text really was only the first of two separate ORCA
        # runs; see docs/trackers/2026-08-job-system-overhaul.md's P6.4 entry.)
        ("opt_freq, generated",
         generated("orca", "opt_freq", "", "hf", {"basis": "sto-3g"}),
         ("opt_freq", ""), "hf"),
        ("hand-written combined Opt Freq", ORCA_OPT_FREQ, ("opt_freq", ""), "dft"),
        ("excited states, generated",
         generated("orca", "single_point", "ee", "dft",
                   {"functional": "b3lyp", "basis": "sto-3g", "n_states": 3}),
         ("single_point", "ee"), "dft"),
        ("hand-written optimization", ORCA_MANUAL_STYLE, ("opt", "min"), "dft"),
        # nroots 3 -- an excited-state calculation, and the only thing in
        # the whole input that says so.
        ("hand-written CASSCF", ORCA_CASSCF, ("single_point", "ee"), "casscf"),
        ("no task keyword at all", ORCA_NO_TASK, ("single_point", "gs"), "mp2"),
    ]
    for label, text, (task, subtype), method in orca_cases:
        r = sniff(text)
        check(f"{label}: engine", r.engine == "orca", f"got {r.engine!r}")
        check(f"{label}: {task}/{subtype} at {method}",
              (r.task, r.subtype, r.method) == (task, subtype, method),
              f"got {r.task}/{r.subtype} at {r.method}")
        check(f"{label}: runnable", r.executable)

    # The multireference root count, read on ORCA the same way it is read
    # on BAGEL. There is no %tddft block in a CASSCF/NEVPT2 input, so
    # nroots is the only thing separating one ground-state energy from a
    # set of vertical excitation energies -- and it counts the ground
    # state, so one root is not an excited-state job.
    one_root = ORCA_CASSCF.replace("nroots 3", "nroots 1")
    r = sniff(one_root)
    check("ORCA: one root stays a ground-state single point",
          (r.task, r.subtype, r.method) == ("single_point", "gs", "casscf"),
          f"got {r.task}/{r.subtype} at {r.method}")

    inline = "! NEVPT2 def2-SVP\n%casscf nel 6 norb 6 nroots 4 end\n* xyz 0 1\nO 0 0 0\n*\n"
    r = sniff(inline)
    check("ORCA: nroots is found in a block written on one line",
          (r.task, r.subtype, r.method) == ("single_point", "ee", "casscf"),
          f"got {r.task}/{r.subtype} at {r.method} (reasons: {list(r.reasons)})")

    # The promotion must not fire on a task that is not a single point,
    # and must not reach past the %casscf block into another one.
    mecp = "! CASSCF cc-pVDZ\n%mecp end\n%casscf nroots 2 end\n* xyz 0 1\nO 0 0 0\n*\n"
    r = sniff(mecp)
    check("ORCA: a crossing-point search stays opt/ci with several roots",
          (r.task, r.subtype) == ("opt", "ci"), f"got {r.task}/{r.subtype}")

    tddft_nroots = "! B3LYP def2-SVP\n%tddft nroots 5 end\n* xyz 0 1\nO 0 0 0\n*\n"
    r = sniff(tddft_nroots)
    check("ORCA: a %tddft block is excited states without needing its root count",
          (r.task, r.subtype, r.method) == ("single_point", "ee", "dft"),
          f"got {r.task}/{r.subtype} at {r.method}")

    print("\n== BAGEL ==")
    # Every BAGEL job type this app builds is CAS-based (see
    # bagel_runner._build_input), so they all carry an active space.
    # Two roots, so every single point below is an excited-state one: on
    # this engine the root count is the only thing that says so, and it
    # counts the ground state.
    CAS = {"basis": "sto-3g", "active_electrons": 4,
           "active_orbitals": 4, "n_states": 2}
    ONE_ROOT = dict(CAS, n_states=1)
    bagel_cases = [
        ("single point, generated",
         generated("bagel", "single_point", "gs", "casscf", dict(CAS)),
         ("single_point", "ee"), "casscf"),
        ("optimization, generated",
         generated("bagel", "opt", "min", "casscf", dict(CAS)),
         ("opt", "min"), "casscf"),
        ("frequencies, generated",
         generated("bagel", "freq", "", "casscf", dict(CAS)),
         ("freq", ""), "casscf"),
        ("one-root CASSCF, generated",
         generated("bagel", "single_point", "gs", "casscf", dict(ONE_ROOT)),
         ("single_point", "gs"), "casscf"),
        ("CASPT2, generated",
         generated("bagel", "single_point", "gs", "caspt2", dict(CAS)),
         ("single_point", "ee"), "caspt2"),
    ]
    for label, text, (task, subtype), method in bagel_cases:
        r = sniff(text)
        check(f"{label}: engine", r.engine == "bagel", f"got {r.engine!r}")
        check(f"{label}: {task}/{subtype}", (r.task, r.subtype) == (task, subtype),
              f"got {r.task}/{r.subtype} (reasons: {list(r.reasons)})")
        check(f"{label}: at {method}", r.method == method,
              f"got {r.method!r} (reasons: {list(r.reasons)})")
        check(f"{label}: runnable", r.executable)

    # The regression this file exists to hold. Every CASSCF input BAGEL
    # accepts opens with an "hf" block, because the SCF orbitals are the
    # starting guess -- reading the first method-shaped section title
    # reported that preamble and called a three-root CASSCF an HF ground
    # state single point. The text is the one a user really pasted, active
    # space and all.
    hand_cas = """\
{ "bagel" : [
  { "title" : "molecule", "basis" : "cc-pvdz", "df_basis" : "cc-pvdz-jkfit",
    "angstrom" : true,
    "geometry" : [ {"atom":"O","xyz":[0.0,0.0,0.0]} ] },
  { "title" : "hf", "charge" : 0, "nopen" : 0 },
  { "title" : "casscf", "nstate" : 3, "nact" : 9, "nclosed" : 23,
    "active" : [21, 22, 24, 25, 27, 28, 29, 30, 37] },
  { "title" : "print", "file" : "orbitals.molden", "orbitals" : true },
  { "title" : "save_ref", "file" : "orbitals" }
] }
"""
    r = sniff(hand_cas)
    check("a pasted CASSCF is not read as its hf preamble", r.method == "casscf",
          f"got {r.method!r} (reasons: {list(r.reasons)})")
    check("and three roots make it an excited-state single point",
          (r.task, r.subtype) == ("single_point", "ee"),
          f"got {r.task}/{r.subtype} (reasons: {list(r.reasons)})")
    check("described as such", "casscf" in r.describe() and "ee" in r.describe(),
          r.describe())

    # The same input with one root is a ground-state calculation, and the
    # promotion must not fire on a coupling, which carries several roots
    # of its own.
    one_root = hand_cas.replace('"nstate" : 3', '"nstate" : 1')
    r = sniff(one_root)
    check("one root stays a ground-state single point",
          (r.task, r.subtype, r.method) == ("single_point", "gs", "casscf"),
          f"got {r.task}/{r.subtype} at {r.method}")

    hand_bagel = """\
{ "bagel" : [
  { "title" : "molecule", "basis" : "svp", "df_basis" : "svp-jkfit",
    "geometry" : [ {"atom":"O","xyz":[0.0,0.0,0.0]} ] },
  { "title" : "forces", "grads" : [ {"title":"force","target":0} ],
    "method" : [ { "title" : "casscf", "nstate" : 2 } ] }
] }
"""
    r = sniff(hand_bagel)
    check("hand-written forces block is a gradient",
          (r.engine, r.task, r.subtype) == ("bagel", "single_point", "grad"),
          f"got {r.engine} {r.task}/{r.subtype}")
    check("with the method read from the nested block", r.method == "casscf",
          f"got {r.method!r} (reasons: {list(r.reasons)})")

    nacme = hand_bagel.replace('"forces"', '"nacme"')
    r = sniff(nacme)
    check("a nacme block is a non-adiabatic coupling",
          (r.task, r.subtype) == ("single_point", "nac"), f"got {r.task}/{r.subtype}")

    print("\n== PySCF -- recognized, never run ==")
    pyscf_cases = [
        ("plain HF script", PYSCF_SCRIPT, ("single_point", "gs"), "hf", "cc-pvdz"),
        ("CASSCF script", PYSCF_CASSCF, ("single_point", "gs"), "casscf", "6-31g"),
        ("optimization script", PYSCF_OPT, ("opt", "min"), "hf", "sto-3g"),
    ]
    for label, text, (task, subtype), method, basis in pyscf_cases:
        r = sniff(text)
        check(f"{label}: recognized as PySCF", r.engine == "pyscf", f"got {r.engine!r}")
        check(f"{label}: classified {task}/{subtype} at {method}",
              (r.task, r.subtype, r.method) == (task, subtype, method),
              f"got {r.task}/{r.subtype} at {r.method}")
        check(f"{label}: basis read as {basis}", r.basis == basis, f"got {r.basis!r}")
        # The one that matters.
        check(f"{label}: NOT executable", r.executable is False)

    print("\n== the shapes each program really writes ==")
    # Method and root-count coverage across all three programs, added
    # when the classifier was hardened -- see
    # docs/trackers/2026-08-bagel-blind-input.md, phase 4. Every case
    # here is a spelling a real input uses, not a synthetic variation:
    # ORCA puts the convergence level and the coordinate system inside
    # the optimization keyword and the approximation family in front of
    # the method, PySCF builds the cheap object before the expensive one
    # that wraps it, and BAGEL writes both a singular and a plural
    # gradient section.
    geom = "\n* xyz 0 1\nO 0 0 0\n*\n"
    orca_shapes = [
        # the optimization keyword is spelled many ways and is one job
        ("! TightOpt B3LYP def2-SVP", ("opt", "min"), "dft"),
        ("! VeryTightOpt BP86 def2-SVP", ("opt", "min"), "dft"),
        ("! COpt PBE0 def2-SVP", ("opt", "min"), "dft"),
        ("! L-Opt BP86 def2-SVP", ("opt", "min"), "dft"),
        ("! TightOpt Freq B3LYP def2-SVP", ("opt_freq", ""), "dft"),
        # the approximation family sits in front of the method
        ("! DLPNO-CCSD(T) cc-pVTZ", ("single_point", "gs"), "ccsd"),
        ("! DLPNO-CCSD(T1) cc-pVTZ", ("single_point", "gs"), "ccsd"),
        ("! DLPNO-MP2 def2-SVP", ("single_point", "gs"), "mp2"),
        ("! RI-MP2 cc-pVDZ", ("single_point", "gs"), "mp2"),
        # ...except STEOM's, which puts it in the middle
        ("! STEOM-DLPNO-CCSD def2-TZVP", ("single_point", "ee"), "eom_ccsd"),
        ("! EOM-CCSD cc-pVDZ", ("single_point", "ee"), "eom_ccsd"),
        # composites, and the wB97/B97 family
        ("! r2SCAN-3c Opt", ("opt", "min"), "dft"),
        ("! B97-3c Opt", ("opt", "min"), "dft"),
        ("! PBEh-3c def2-SVP", ("single_point", "gs"), "dft"),
        ("! wB97M-V def2-TZVP", ("single_point", "gs"), "dft"),
        ("! wB97X-D4 def2-SVP", ("single_point", "gs"), "dft"),
        ("! M06 def2-SVP", ("single_point", "gs"), "dft"),
        ("! r2SCAN def2-SVP", ("single_point", "gs"), "dft"),
        # HF-3c is a composite Hartree-Fock method, not a functional, and
        # has to beat the "-3c means DFT" rule
        ("! HF-3c Opt", ("opt", "min"), "hf"),
        ("! UHF cc-pVDZ", ("single_point", "gs"), "hf"),
        ("! ROHF sto-3g", ("single_point", "gs"), "hf"),
    ]
    for line, (task, subtype), method in orca_shapes:
        r = sniff(line + geom)
        check(f"ORCA {line[2:]}", (r.task, r.subtype, r.method) == (task, subtype, method),
              f"got {r.task}/{r.subtype} at {r.method} (reasons: {list(r.reasons)})")

    # A transition-state search is a real ORCA job this app has no task
    # for. Reading it as opt/min would offer to build something that
    # relaxes the structure off the saddle point, and reading "! OptTS
    # Freq" as a plain frequency job silently drops the search. Reported
    # as unidentified, which still runs verbatim.
    for line in ("! OptTS B3LYP def2-SVP", "! OptTS Freq B3LYP def2-SVP",
                 "! ScanTS PBE0 def2-SVP"):
        r = sniff(line + geom)
        check(f"ORCA {line[2:]} is not claimed as any job type",
              r.engine == "orca" and not r.confident and not r.task,
              f"got {r.task}/{r.subtype} at {r.method} confident={r.confident}")
        check(f"ORCA {line[2:]} still runs verbatim", r.executable)

    bagel_shapes = [
        # "force" singular and "forces" plural are both gradient sections
        ("singular force section", [{"title": "hf"},
                                    {"title": "force", "method": [{"title": "casscf", "nstate": 2}]}],
         ("single_point", "grad"), "casscf"),
        # smith is how BAGEL runs CASPT2, and it follows the casscf block
        ("CASPT2 through smith", [{"title": "hf"}, {"title": "casscf", "nstate": 3},
                                  {"title": "smith", "method": "caspt2"}],
         ("single_point", "ee"), "caspt2"),
        ("an optimization of the CASPT2 surface",
         [{"title": "optimize", "method": [{"title": "casscf", "nstate": 2},
                                           {"title": "smith", "method": "caspt2"}]}],
         ("opt", "min"), "caspt2"),
        ("plain HF", [{"title": "hf"}], ("single_point", "gs"), "hf"),
        ("Kohn-Sham DFT", [{"title": "ks", "xc_func": "b3lyp"}], ("single_point", "gs"), "dft"),
        ("MP2", [{"title": "hf"}, {"title": "mp2"}], ("single_point", "gs"), "mp2"),
        ("a one-root CASSCF Hessian",
         [{"title": "hf"}, {"title": "casscf", "nstate": 1}, {"title": "hessian"}],
         ("freq", ""), "casscf"),
    ]
    molecule_block = {"title": "molecule", "basis": "svp", "df_basis": "svp-jkfit",
                      "geometry": [{"atom": "O", "xyz": [0.0, 0.0, 0.0]}]}
    for label, blocks, (task, subtype), method in bagel_shapes:
        r = sniff(json.dumps({"bagel": [molecule_block, *blocks]}))
        check(f"BAGEL {label}", (r.task, r.subtype, r.method) == (task, subtype, method),
              f"got {r.task}/{r.subtype} at {r.method} (reasons: {list(r.reasons)})")

    # Several roots and a coupling section is a coupling, not a set of
    # excitation energies -- the promotion fires only from gs.
    r = sniff(json.dumps({"bagel": [molecule_block, {"title": "hf"},
                                    {"title": "nacme",
                                     "method": [{"title": "casscf", "nstate": 2}]}]}))
    check("BAGEL a two-root nacme section is still a coupling",
          (r.task, r.subtype, r.method) == ("single_point", "nac", "casscf"),
          f"got {r.task}/{r.subtype} at {r.method}")

    pyscf_shapes = [
        ("state-averaged CASSCF", """
from pyscf import gto, scf, mcscf
mf = scf.RHF(gto.M(atom='O 0 0 0', basis='6-31g')).run()
mc = mcscf.CASSCF(mf, 6, 6).state_average_([1/3, 1/3, 1/3])
mc.kernel()
""", ("single_point", "ee"), "casscf"),
        ("CASCI with nroots", """
from pyscf import gto, scf, mcscf
mf = scf.RHF(gto.M(atom='O 0 0 0', basis='sto-3g')).run()
mc = mcscf.CASCI(mf, 4, 4)
mc.fcisolver.nroots = 4
mc.kernel()
""", ("single_point", "ee"), "casscf"),
        ("a one-root CASSCF", """
from pyscf import gto, scf, mcscf
mf = scf.RHF(gto.M(atom='O 0 0 0', basis='sto-3g')).run()
mcscf.CASSCF(mf, 4, 4).kernel()
""", ("single_point", "gs"), "casscf"),
        ("NEVPT2 on top of CASSCF", """
from pyscf import gto, scf, mcscf, mrpt
mf = scf.RHF(gto.M(atom='O 0 0 0', basis='cc-pvdz')).run()
mc = mcscf.CASSCF(mf, 6, 6).run()
mrpt.NEVPT(mc).kernel()
""", ("single_point", "gs"), "casscf"),
        ("EOM-CCSD", """
from pyscf import gto, scf, cc
mf = scf.RHF(gto.M(atom='O 0 0 0', basis='cc-pvdz')).run()
mycc = cc.CCSD(mf).run()
mycc.eomee_ccsd_singlet(nroots=3)
""", ("single_point", "ee"), "eom_ccsd"),
        ("an unrestricted DFT optimization", """
from pyscf import gto, dft
from pyscf.geomopt.geometric_solver import optimize
mf = dft.UKS(gto.M(atom='O 0 0 0', basis='def2-svp', spin=2))
optimize(mf)
""", ("opt", "min"), "dft"),
    ]
    for label, script, (task, subtype), method in pyscf_shapes:
        r = sniff(script)
        check(f"PySCF {label}", (r.task, r.subtype, r.method) == (task, subtype, method),
              f"got {r.task}/{r.subtype} at {r.method} (reasons: {list(r.reasons)})")
        # The load-bearing invariant, restated for every one of them.
        check(f"PySCF {label}: still never executable", not r.executable)

    print("\n== nothing recognizable ==")
    for label, text in (("prose", "please run a calculation on benzene for me"),
                        ("empty", ""), ("an xyz file", "3\nwater\nO 0 0 0\n")):
        r = sniff(text)
        check(f"{label} is not claimed as any engine", r.engine is None,
              f"got {r.engine!r}")
        check(f"{label} is not executable", r.executable is False)

    print("\n== the draft flow uses it ==")
    v = validate_draft({"task": "blind", "params": {"raw_input_text": ORCA_MANUAL_STYLE}}, {})
    check("a pasted ORCA input needs no engine question",
          v.status == "ready" and v.draft["resolved_engine"] == "orca",
          f"status={v.status!r} ask={v.ask_user_exactly!r}")
    check("and the user is told what it was recognized as",
          any("ORCA input for a opt/min" in n for n in v.notes), f"notes={list(v.notes)}")
    check("and offered the structured alternative",
          any("run it verbatim" in n for n in v.notes), f"notes={list(v.notes)}")

    v = validate_draft({"task": "blind", "engine": "bagel",
                        "params": {"raw_input_text": ORCA_MANUAL_STYLE}}, {})
    check("a stated engine that contradicts the text is queried, not overridden",
          v.status == "incomplete" and v.asking_for == "engine",
          f"status={v.status!r} asking_for={v.asking_for!r}")

    v = validate_draft({"task": "blind", "params": {"raw_input_text": PYSCF_SCRIPT}}, {})
    check("a pasted PySCF script is declined for blind execution",
          v.status == "unavailable", f"status={v.status!r}")
    check("with the offer to build it properly instead",
          "never runs a pasted Python script" in v.ask_user_exactly,
          v.ask_user_exactly[:200])

    total = PASS + FAIL
    print(f"\n{PASS}/{total} checks passed")
    if FAIL:
        print(f"[FAIL] {FAIL} check(s) failed")
        return 1
    print("[PASS] ALL CHECKS PASSED")
    return 0


if __name__ == "__main__":
    sys.exit(main())
